timeout: 5
serial: yes

/spctrx v0.1
    protocol: limine
    path: boot():/boot/kernel.sys
    comment: "spctrx v0.1 (www.github.com/1mvghost/spctrx)"

/spctrx v0.1 ( LOWER RES )
    protocol: limine
    path: boot():/boot/kernel.sys
    resolution: 1024x768x32
    comment: "spctrx v0.1 (www.github.com/1mvghost/spctrx)"
